export const INDUSTRY_OPTIONS: string[] = [
  'Administración y Gestión Empresarial',
  'Agricultura y Ganadería',
  'Agroindustria',
  'Alimentación y Bebidas',
  'Arte y Entretenimiento',
  'Automotriz',
  'Aviación y Aeronáutica',
  'Banca y Finanzas',
  'Bienes Raíces e Inmobiliaria',
  'Biotecnología',
  'Comercio Electrónico',
  'Construcción e Infraestructura',
  'Consultoría de Negocios',
  'Consultoría Tecnológica',
  'Defensa y Seguridad',
  'Deportes y Recreación',
  'Desarrollo de Software',
  'Distribución y Logística',
  'Economía Solidaria y Cooperativas',
  'Educación y Formación',
  'Electrónica y Semiconductores',
  'Energía Renovable',
  'Energía y Utilities',
  'Farmacéutica',
  'Gobierno y Sector Público',
  'Hotelería y Turismo',
  'Industria Química',
  'Ingeniería y Proyectos',
  'Legal y Servicios Jurídicos',
  'Manufactura e Industria',
  'Marketing y Publicidad',
  'Medios de Comunicación',
  'Medio Ambiente y Sostenibilidad',
  'Minería',
  'Moda y Textil',
  'ONG y Sector Social',
  'Petróleo y Gas',
  'Pesca y Acuicultura',
  'Recursos Humanos',
  'Retail y Comercio',
  'Salud y Medicina',
  'Seguros',
  'Servicios de TI',
  'Servicios Financieros',
  'Silvicultura y Forestal',
  'Telecomunicaciones',
  'Transporte Marítimo',
  'Transporte Terrestre',
  'Turismo y Viajes',
  'Veterinaria y Mascotas',
]

export const COUNTRY_OPTIONS: string[] = [
  'Afganistán', 'Albania', 'Alemania', 'Andorra', 'Angola', 'Antigua y Barbuda',
  'Arabia Saudita', 'Argelia', 'Argentina', 'Armenia', 'Australia', 'Austria',
  'Azerbaiyán', 'Bahamas', 'Bangladés', 'Barbados', 'Baréin', 'Bélgica',
  'Belice', 'Benín', 'Bielorrusia', 'Bolivia', 'Bosnia y Herzegovina', 'Botsuana',
  'Brasil', 'Brunéi', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Bután',
  'Cabo Verde', 'Camboya', 'Camerún', 'Canadá', 'Catar', 'Chad',
  'Chile', 'China', 'Chipre', 'Colombia', 'Comoras', 'Congo',
  'Corea del Norte', 'Corea del Sur', 'Costa de Marfil', 'Costa Rica', 'Croacia', 'Cuba',
  'Dinamarca', 'Dominica', 'Ecuador', 'Egipto', 'El Salvador', 'Emiratos Árabes Unidos',
  'Eritrea', 'Eslovaquia', 'Eslovenia', 'España', 'Estados Unidos', 'Estonia',
  'Etiopía', 'Filipinas', 'Finlandia', 'Fiyi', 'Francia', 'Gabón',
  'Gambia', 'Georgia', 'Ghana', 'Granada', 'Grecia', 'Guatemala',
  'Guinea', 'Guinea Ecuatorial', 'Guinea-Bisáu', 'Guyana', 'Haití', 'Honduras',
  'Hungría', 'India', 'Indonesia', 'Irak', 'Irán', 'Irlanda',
  'Islandia', 'Islas Marshall', 'Islas Salomón', 'Israel', 'Italia', 'Jamaica',
  'Japón', 'Jordania', 'Kazajistán', 'Kenia', 'Kirguistán', 'Kiribati',
  'Kuwait', 'Laos', 'Lesoto', 'Letonia', 'Líbano', 'Liberia',
  'Libia', 'Liechtenstein', 'Lituania', 'Luxemburgo', 'Madagascar', 'Malasia',
  'Malaui', 'Maldivas', 'Malí', 'Malta', 'Marruecos', 'Mauricio',
  'Mauritania', 'México', 'Micronesia', 'Moldavia', 'Mónaco', 'Mongolia',
  'Montenegro', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
  'Nicaragua', 'Níger', 'Nigeria', 'Noruega', 'Nueva Zelanda', 'Omán',
  'Países Bajos', 'Pakistán', 'Palaos', 'Panamá', 'Papúa Nueva Guinea', 'Paraguay',
  'Perú', 'Polonia', 'Portugal', 'Reino Unido', 'República Centroafricana', 'República Checa',
  'República Democrática del Congo', 'República Dominicana', 'Ruanda', 'Rumanía', 'Rusia', 'Samoa',
  'San Cristóbal y Nieves', 'San Marino', 'San Vicente y las Granadinas', 'Santa Lucía', 'Santo Tomé y Príncipe', 'Senegal',
  'Serbia', 'Seychelles', 'Sierra Leona', 'Singapur', 'Siria', 'Somalia',
  'Sri Lanka', 'Sudáfrica', 'Sudán', 'Sudán del Sur', 'Suecia', 'Suiza',
  'Surinam', 'Tailandia', 'Tanzania', 'Timor Oriental', 'Togo', 'Tonga',
  'Trinidad y Tobago', 'Túnez', 'Turkmenistán', 'Turquía', 'Tuvalu', 'Ucrania',
  'Uganda', 'Uruguay', 'Uzbekistán', 'Vanuatu', 'Venezuela', 'Vietnam',
  'Yemen', 'Yibuti', 'Zambia', 'Zimbabue',
]


export const SIZE_OPTIONS: string[] = [
  '1-10 empleados',
  '11-50 empleados',
  '51-200 empleados',
  '201-500 empleados',
  '500+ empleados',
]
